#!/usr/bin/env bash
set -euo pipefail

# enable systemd user services for a list of services
enable_user_services() { 
  echo "Enabling user services..."

  systemctl --user enable niri.service
  systemctl --user enable dms
  systemctl --user add-wants niri.service dms
}

# Main
enable_user_services
